2024-01-11 19:15:12,264 INFO    MainThread:973565 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-01-11 19:15:12,264 INFO    MainThread:973565 [wandb_setup.py:_flush():76] Configure stats pid to 973565
2024-01-11 19:15:12,264 INFO    MainThread:973565 [wandb_setup.py:_flush():76] Loading settings from /home/shared/.config/wandb/settings
2024-01-11 19:15:12,264 INFO    MainThread:973565 [wandb_setup.py:_flush():76] Loading settings from /home/shared/armeet/ultrasound/notebooks/wandb/settings
2024-01-11 19:15:12,264 INFO    MainThread:973565 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-11 19:15:12,265 INFO    MainThread:973565 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-11 19:15:12,265 INFO    MainThread:973565 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-11 19:15:12,265 INFO    MainThread:973565 [wandb_init.py:_log_setup():526] Logging user logs to /home/shared/armeet/ultrasound/notebooks/wandb/run-20240111_191512-aceopgg3/logs/debug.log
2024-01-11 19:15:12,265 INFO    MainThread:973565 [wandb_init.py:_log_setup():527] Logging internal logs to /home/shared/armeet/ultrasound/notebooks/wandb/run-20240111_191512-aceopgg3/logs/debug-internal.log
2024-01-11 19:15:12,265 INFO    MainThread:973565 [wandb_init.py:init():566] calling init triggers
2024-01-11 19:15:12,265 INFO    MainThread:973565 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2024-01-11 19:15:12,265 INFO    MainThread:973565 [wandb_init.py:init():591] re-initializing run, found existing run on stack: o9gzaluq
2024-01-11 19:15:12,266 INFO    MainThread:973565 [wandb_run.py:_finish():1962] finishing run armeet-team/ultrasound-trial-1d/o9gzaluq
2024-01-11 19:15:12,266 INFO    MainThread:973565 [jupyter.py:save_history():445] not saving jupyter history
2024-01-11 19:15:12,266 INFO    MainThread:973565 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-11 19:15:12,266 INFO    MainThread:973565 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-01-11 19:15:12,266 INFO    MainThread:973565 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-01-11 19:15:12,266 INFO    MainThread:973565 [wandb_run.py:_restore():2185] restore
2024-01-11 19:15:12,266 INFO    MainThread:973565 [wandb_run.py:_restore():2191] restore done
2024-01-11 19:15:39,971 INFO    MainThread:973565 [wandb_init.py:init():616] starting backend
2024-01-11 19:15:39,971 INFO    MainThread:973565 [wandb_init.py:init():620] setting up manager
2024-01-11 19:15:39,972 INFO    MainThread:973565 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-01-11 19:15:39,972 INFO    MainThread:973565 [wandb_init.py:init():628] backend started and connected
2024-01-11 19:15:39,976 INFO    MainThread:973565 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-11 19:15:39,976 INFO    MainThread:973565 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-11 19:15:39,976 INFO    MainThread:973565 [wandb_init.py:init():720] updated telemetry
2024-01-11 19:15:39,979 INFO    MainThread:973565 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
